apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "relayer.fullname" . }}
  labels:
    {{- include "relayer.labels" . | nindent 4 }}
data:
  ETHEREUM_API_ENDPOINT: {{ .Values.app.ethereumApiEndpoint | quote }}
  LIGHT_NODE_ENDPOINT: {{ .Values.app.lightNodeEndpoint | quote }}
  TARAXA_NODE_URL: {{ .Values.app.taraxaNodeUrl | quote }}
  TARAXA_CONTRACT_ADDRESS: {{ .Values.app.taraxaContractAddress | quote }}